### ISSUE TITLE
LootControl needs a TShock 5 update

### ISSUE THREAD

**Issue by Kojirremer** [beerik94/LootControl#5]
Hello there. The plugin crashes on startup when trying to run it on latest TShock pre-release.
Here is the crash log:
```[11/03/22 00:17:56] [Server API] Error: LootControl.dll was built for X86 but expected it to be compatible with X64.
[11/03/22 00:17:56] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Failed to load assembly "LootControl.dll".
 ---> System.IO.FileLoadException: Could not load file or assembly 'LootControl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 343
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 414
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game) in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs:line 118
   at TerrariaApi.Server.HookManager.InitialiseAPI() in /home/runner/work/TShock/TShock/TerrariaServerAPI/TerrariaServerAPI/TerrariaApi.Server/HookManager.cs:line 29```

Sorry to bother you, and thanks in advance.

**Comment by beerik94** [comment]
I haven't done any TShock related stuff for a long time. But i'll see what I can do.

**Comment by beerik94** [comment]
@Kojirremer I released a 2.0.0-alpha which uses the TShock 5 api.
I currently can not test if this works so if you can test it and tell me then i'll release it as stable.

**Comment by Kojirremer** [comment]
I'm sorry, but ever since TShock switched to .NET 6 I haven't had the chance to try compiling plugins, so I can't really test. Average forked the plugin and released a working version; don't know if it's 100% working but so far everything seems OK.
